eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
