spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mosb_catalog;DB_CLOSE_DELAY=-1
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: update